enquetes/urls.py
from django.urls import path
from . import views

# mapeamento das url's da aplicação enquetes
# name é utilizado nas renderizações:
# { url enquetes:index [params] }

app_name="enquetes" # namespace enquetes
urlpatterns = [
    path("", views.index, name="index"),
    path("sobre/", views.sobre, name="sobre"),
    path("visualizarEnquete/<int:pergunta_id>/", views.visualizarEnquete, name="visualizarEnquete"),
    path("criarEnquete/", views.criarEnquete, name="criarEnquete"),
    path("criarEnquetePost/", views.criarEnquetePost, name="criarEnquetePost" ),
    path("deletarEnquete/<int:pergunta_id>", views.deletarEnquete, name="deletarEnquete" ),
    path("editarEnquetePatch/<int:pergunta_id>", views.editarEnquetePatch, name="editarEnquetePatch")
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

# mapeamento de urls do projeto como um todo.

urlpatterns = [
    path("enquetes/", include("enquetes.urls")), #aplicação enquetes
    path('admin/', admin.site.urls)
]

enquetes/models.py
import datetime

from django.db import models

# modelos de dados da aplicação para SGBD relacional (Vide documentação)

class Pergunta( models.Model ):

    texto   = models.CharField( max_length=200 )
    date    = models.DateTimeField( "data da publicação" )

    def help(self):
        print('campos: {texto:str, date:datetime}')

    # Pergunta.objects.all() interactive prompt
    def __str__(self):
        return f'texto: {self.texto}, date: {self.date}'

    def perguntado_recentemente(self):
        return self.date >= timezone.now() - datetime.timedelta(days=1)

class Escolha( models.Model ):

    pergunta    = models.ForeignKey( Pergunta, on_delete=models.CASCADE )
    texto       = models.CharField( max_length=200 )
    votes       = models.IntegerField( default=0 )

    def help(self):
        print('campos: {pergunta:FK, texto:str, votes:int}')

    def __str__(self):
        return f'pergunta: {self.pergunta}, texto: {self.texto}, votes: {self.votes}'

enquetes/views.py
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from .models import Pergunta, Escolha

# views da aplicação enquetes




def index(request):
    dados = ''
    contexto = {
        "perguntas": {}
    }
    try:
        contexto['perguntas'] = Pergunta.objects.order_by( "texto" )
    except:
        print(f"LOG enquetes/ consulta falhou")
    return render( request, "enquetes/index.html", contexto )




def sobre(request):
    return HttpResponse( '<p> gerencie enquetes </p><a href="javascript:history.back()"> inicio </a>' )




def criarEnquete(request):
    return render( request, "enquetes/criarEnquete.html", {} )




def criarEnquetePost( request ):
    try:
        Texto = request.POST["texto"]
        escolhas = json.loads( request.POST["perguntas"] ) #{"opcoes":[<str>,<str>...]}


        # cria enquete primeiro
        novaEnquete = Pergunta( texto=Texto, date=timezone.now() )
        novaEnquete.save()

        if "opcoes" in escolhas and len(escolhas["opcoes"]) > 0 :

            for elemento in escolhas["opcoes"]:
                escolha = Escolha( pergunta=novaEnquete, texto=elemento, votes=0 )
                escolha.save()

        else:
            err = '"escolhas" não presentes em "perguntas" ou lista vazia: ' + json.dumps(escolhas)
            raise Exception( err )

    except BaseException as e:
        print(f"FALHA: {e} ")
        return render( request, "enquetes/erro.html" )
        novaEnquete.delete() #operação atômica !

    return HttpResponseRedirect( reverse( "enquetes:index" ) )





# http.param: pergunta_id
def visualizarEnquete(request, pergunta_id):
    consulta = ''
    opcoes = ''
    contexto = { }
    try:
        consulta =  Pergunta.objects.get( id=pergunta_id )
        opcoes = Escolha.objects.filter( pergunta=( Pergunta.objects.get(id= pergunta_id ) ) )
        contexto = {
            "pergunta_id": pergunta_id,
            "consulta": consulta,
            "opcoes": opcoes
        }
    except BaseException as e:
        print(f"FALHA: {e} ")
        return render( request, "enquetes/erro.html" )

    return render( request, "enquetes/visualizarEnquete.html", contexto )




def editarEnquetePatch(request, pergunta_id):
    try:
        alvo = Pergunta.objects.get(id=pergunta_id)
        alvo.texto = request.POST["texto"]
        alvo.save()
    except:
        return render( request, "enquetes/erro.html" )

    return HttpResponseRedirect( reverse( "enquetes:index" ) )




def deletarEnquete(request, pergunta_id):
    try:
        alvo = Pergunta.objects.get(id=pergunta_id)
        alvo.delete()
    except:
        return render( request, "enquetes/erro.html" )

    return HttpResponseRedirect( reverse( "enquetes:index" ) )




def visualizarEnquetes(request):
    pass

enquetes/templates/enquetes/criarEnquete.html
{# criação de enquete #}

<form action="{% url "enquetes:criarEnquetePost" %}" method="post">
  {% csrf_token %}
  <label for="texto"></label>
  <input type="text" name="texto" id="texto" placeholder="pergunta" required>
  
  <!-- Contém dados em json extraidos dos <p> internos à #listaEscolhas -->
  <input type="hidden" name="perguntas" id="perguntas" value="" >

  <button type="submit" onclick="gerarDados()"> LANÇAR ENQUETE </button>
</form>

<div id="listaEscolhas">
  {# adição ou remoção dinâmica de opções em um <p></p> #}
</div>

<div id="contole">
  <input  id="textoOpt" type="text" placeholder="texto da opção">
  <button id="add" onclick="add()"> + </button>
  <button id="rem" onclick="rem()"> - </button>
</div>

<a href="{% url "enquetes:index" %}"> cancelar </a>

<script type="text/javascript">
  /* script responsável por adição ou remoção de opções da enquete */


  // adiciona escolha
  function add()
  {
    let listaEscolhas = document.getElementById( "listaEscolhas" );
    let novaOpcao = document.createElement('p');
    let textoOpt  = document.getElementById("textoOpt");

    if ( textoOpt.value == '' )
    {
      window.alert( "texto da opção não pode estar vazio" );
      return;
    }

    novaOpcao.innerHTML = textoOpt.value;
    listaEscolhas.appendChild( novaOpcao );
    textoOpt.value = "";
  }

  // remove escolha
  function rem( texto="-" )
  {
    let listaEscolhas = document.getElementById( "listaEscolhas" );
    if ( listaEscolhas.lastChild != null )
    {
      listaEscolhas.removeChild( listaEscolhas.lastChild );
    }
  }

  /* extrai dados de #listaEscolhas e os atribui em JSON
     ao value de um hidden. Trabalha quando submit é pressionado.
  */
  function gerarDados()
  {
    let listaEscolhas = document.getElementById( "listaEscolhas" );
    let perguntas = document.getElementById( "perguntas" );

    let dados = {"opcoes":[]} ;

    while ( listaEscolhas.lastChild != null )
    {
      let removido = listaEscolhas.removeChild( listaEscolhas.lastChild );
      dados.opcoes.push( removido.innerText );
    }

    for ( let i = 0; i < dados.opcoes.length; i++ )
    {
      if ( dados.opcoes[i] == null ) dados.opcoes.pop(i);
    }
    perguntas.value = JSON.stringify( dados );
    
  }

</script>

enquetes/templates/enquetes/erro.html
<h2> Falhou </h2>
<p> A ação falhou ! </p>
<a href="{% url "enquetes:index" %}" > voltar ao inicio </a>

enquetes/templates/enquetes/index.html
<h1> A APLICAÇÃO DAS ENQUETES </h1>
<h2> Enquetes lançadas: </h2>
{% if perguntas == '' %}
  <p> nenhuma enquete encontrada </p>
{% else %}
<ul>
  {% for pergunta in perguntas %}
  <li> <a href="visualizarEnquete/{{ pergunta.id }}/"> {{ pergunta.texto }} </a> </li>
  {% endfor %}
</ul>
{% endif %}

<h2> Lançar uma nova enquete ! </h2>
<a href="criarEnquete/"> criarEnquete </a>

enquetes/templates/enquetes/quadro.html
<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta charset="utf-8">
		<meta name="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="aplicação de enquetes. LPLA-br">
		<link rel="stylesheet" href="./css/style.css">
		<title> Enquetes </title>
	</head>
  <body>
    <!-- conteúdo variável -->
  </body>
</html>

enquetes/templates/enquetes/visualizarEnquete.html
{# requer: consulta, pergunta_id #}

{% if consulta == '' and opcoes == '' %}
  <h1> BUSCA SEM RESULTADOS </h1>
  <p> {{consulta}} </p>
{% else %}
  <h1> ENQUETE NÚMERO {{ pergunta_id }} </h1>
  <p> {{ consulta.texto }} </p>
  <small> criado em: {{ consulta.date }} </small>

  {# POST {voto} #}
  <form action="" method="post">
    <fieldset>
      {% for opt in opcoes %}
      <label for="{{opt.texto}}"> {{opt.texto}} </label>
      <input type="radio" id="{{opt.texto}}" name="voto" value="{{opt.texto}}">
      {% endfor %}
    </fieldset>
  </form>

{% endif %}

{# utilizando name definido em urls.py #}
<button><a href="{% url "enquetes:index" %}"> início </a></button>

{# dispara requisição de deleção de enquete deletarEnquete/:id/ #}
<button><a href="{% url "enquetes:deletarEnquete" pergunta_id %}"> DELETE </a></button>

<br><br>

<h2> Editar esta enquete </h2>
<form action="{% url "enquetes:editarEnquetePatch" pergunta_id %}" method="patch">
  {% csrf_token %}
  <label for="texto"></label>
  <input type="text" name="texto" id="texto" required>
  <button type="submit"> EDITAR </button>
</form>